"""Add shopping and meal planning models

Revision ID: 9d7223f8cc90
Revises: 03d9762722ed
Create Date: 2025-07-03 01:29:20.624691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9d7223f8cc90'
down_revision: Union[str, Sequence[str], None] = '03d9762722ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopping_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('recipe', 'manual', name='shopping_source'), nullable=False),
    sa.Column('have', sa.Boolean(), nullable=False),
    sa.Column('state_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('meal_selections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_name', sa.String(length=255), nullable=False),
    sa.Column('main_recipe_id', sa.Integer(), nullable=False),
    sa.Column('side_recipe_1_id', sa.Integer(), nullable=True),
    sa.Column('side_recipe_2_id', sa.Integer(), nullable=True),
    sa.Column('side_recipe_3_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_recipe_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_recipe_1_id'], ['recipe.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['side_recipe_2_id'], ['recipe.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['side_recipe_3_id'], ['recipe.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_meal_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal_selections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_meal_states')
    op.drop_table('meal_selections')
    op.drop_table('shopping_states')
    op.drop_table('shopping_items')
    # ### end Alembic commands ###
