"""update recipe image paths to dual default and banner paths

Revision ID: a72f23af2b57
Revises: f73a0850134f
Create Date: 2025-08-28 13:09:38.062045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72f23af2b57'
down_revision: Union[str, Sequence[str], None] = 'f73a0850134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('reference_image_path', sa.String(), nullable=True))
    op.add_column('recipe', sa.Column('banner_image_path', sa.String(), nullable=True))
    op.drop_column('recipe', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image_path', sa.VARCHAR(), nullable=True))
    op.drop_column('recipe', 'banner_image_path')
    op.drop_column('recipe', 'reference_image_path')
    # ### end Alembic commands ###
