"""add notes field to recipe table

Revision ID: f73a0850134f
Revises: 9d7223f8cc90
Create Date: 2025-08-10 12:18:31.155770

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f73a0850134f'
down_revision: Union[str, Sequence[str], None] = '9d7223f8cc90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'notes')
    # ### end Alembic commands ###
